# Generated by Django 4.1 on 2022-08-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('reg_data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
