# Generated by Django 4.1 on 2023-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iden', '0003_dossier_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TG_Users',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('reg_data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Репликант',
                'verbose_name_plural': 'Репликанты',
                'ordering': ['reg_data'],
            },
        ),
    ]
