# Generated by Django 4.1 on 2023-09-14 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iden', '0004_tg_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('character_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('char_instructions', models.TextField()),
                ('greet_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_response', models.TextField()),
                ('user_response', models.TextField()),
                ('involved_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iden.characters')),
                ('involved_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iden.tg_users')),
            ],
        ),
        migrations.AddField(
            model_name='tg_users',
            name='character_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iden.characters'),
        ),
    ]
